# Generated by Django 5.2 on 2025-05-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyApp', '0002_rename_price_per_night_property_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('office', 'Office'), ('land', 'Land')], default='apartment', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='cover_image',
            field=models.ImageField(upload_to='property_images/'),
        ),
    ]
