# Generated by Django 5.2 on 2025-05-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyApp', '0003_property_is_booked_property_property_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='image',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='cover_image',
            field=models.ImageField(default='path_to_default_image.jpg', upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('office', 'Office'), ('land', 'Land')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
