# Generated by Django 5.2 on 2025-05-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyApp', '0004_remove_property_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='cover_image',
            field=models.ImageField(blank=True, default='property_images/default.jpg', null=True, upload_to='property_images/'),
        ),
    ]
